spring:
  data:
    mongodb:
      database: consistent
  application:
    name: consistentHash

hash:
  function: md5 #custom
  consistent: true
  node-nums: 100

server:
  infra: redis
  host: localhost
logging:
  level:
    root: info
